apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldcup2026-app.fullname" . }}
  labels:
    {{- include "worldcup2026-app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
