apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldcup2026-app.postgresFullname" . }}
  labels:
    {{- include "worldcup2026-app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
