apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worldcup2026-app.postgresFullname" . }}
  labels:
    {{- include "worldcup2026-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "worldcup2026-app.postgresFullname" . }}-secret
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.user | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.user | quote }}]
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
            - name: initsql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "worldcup2026-app.postgresFullname" . }}-pvc
        - name: initsql
          configMap:
            name: {{ include "worldcup2026-app.postgresFullname" . }}-initsql
