apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "worldcup2026-app.postgresFullname" . }}-pvc
  labels:
    {{- include "worldcup2026-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
